### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by asperan** [Palleri/dockcheck-web#2]
Hi!

I have seen your project on the dockcheck repository and, while I can find it useful, it doesn't seem to have a license.

Because of this, this project is not usable/forkable/distributable/modifiable by any person other than the creator, you:

> To use a piece of software, whether it’s open source or commercial, you need some grant of rights. In the U.S. and many other places, creative work (including software) is protected by exclusive copyright by default. This means that no one can legally use, copy, distribute, or modify that software without explicit permission from the creator/author. This permission comes in the form of a license that grants the right to do so. Without that license, the baseline assumption is that you do not have permission to use the software.

([Source](https://www.synopsys.com/blogs/software-security/unlicensed-open-source-scenarios/))

I suggest you to [choose a license](https://choosealicense.com/licenses/), so that anybody can help you!

Anyway, good job and keep up the good work!

**Comment by Palleri** [comment]
Hi, thank you for your input. I will definitely look in to this.

**Comment by Palleri** [comment]
Updated license.
Thank you once again!
