### ISSUE TITLE
Container restart required for update

### ISSUE THREAD

**Issue by jcheroske** [Palleri/dockcheck-web#6]
If I update an image and restart the associated container, I would expect dockcheck-web to update the list of containers needing updates when I refresh its webpage. But the behavior I'm seeing is that the list is not updated unless I restart dockcheck-web's container.

**Comment by Palleri** [comment]
Hi, are you using the "Check for updates" button on the page?

**Comment by jcheroske** [comment]
Lol, nope. Didn't even see it! All seems good.
